### Ping
GET {{url}}/{{rest}}/ping


### Login
POST {{url}}/{{rest}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "daniel@daniel",
  "password": "test-pw"
}

> {%
var parsed = JSON.parse(response.body);
client.global.set("auth_token", parsed.access_token);
%}

### Login
POST {{url}}/{{rest}}/register


### upload
POST {{url}}/{{rest}}/upload


### Serve
GET {{url}}/{{rest}}/serve