version: '3.1'

services:
  # see: https://hub.docker.com/_/postgres
  db:
    image: postgres
    env_file:
      - user.env # configure postgres vars
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres:/data/postgres

  app:
    image: little-api:latest
    ports:
      - "8090:8090"
    depends_on:
      - "db"

volumes:
  postgres: